### ISSUE TITLE
add ORCIDs again?

### ISSUE THREAD

**Issue by egonw** [wikipathways/old-rwikipathways#1]
@AlexanderPico, do you mind if I add the ORCIDs again? That's supported by Bioconductor.

**Comment by AlexanderPico** [comment]
Sure. Did I remove orcids? Sorry. Where?

**Comment by egonw** [comment]
It got removed in this commit, check line 7: https://github.com/wikipathways/rwikipathways/commit/31ea5c2aa34ca0c23848434d2628129a2a0d8ae3#diff-35ba4a2677442e210c23a00a5601aba3L7

**Comment by egonw** [comment]
I'll add them again...
