### ISSUE TITLE
remaining BiocCheck issues

### ISSUE THREAD

**Issue by egonw** [wikipathways/old-rwikipathways#2]
Remainin BiocCheck errors:

- [x] "At least 80% of man pages documenting exported objects must have runnable examples. The following pages do not:"
- [x] "Maintainer must register at the support site; visit https://support.bioconductor.org/accounts/signup/ ."        

@AlexanderPico, for the second item, I am signed up (I think, because it does not give that error for BridgeDbR). Can you plz sign up too?

**Comment by AlexanderPico** [comment]
How do you run that? I want to see "The following pages do not:"

I tried this:
```
install.packages("BiocCheck")
  Warning in install.packages :
    package ‘BiocCheck’ is not available (for R version 3.3.3)
```

Do I have to update to 3.4 to run this check?  I'd rather not so that I can easily test/dev for support back to 3.3.

**Comment by egonw** [comment]
It's a BioConductor package, so you need to source their script first... See the BiocCheck package page on BC... (From phone)

**Comment by AlexanderPico** [comment]
Got it!

**Comment by AlexanderPico** [comment]
Ok. I have the list of man pages to fix (answer: all of them) :)

And I'm now a maintainer. But still seeing error. I noticed that in BridgeDbR you used egon.willighagen@gmail.com. Maybe only that email is registered as a maintainer?

**Comment by AlexanderPico** [comment]
fixed with https://github.com/wikipathways/rwikipathways/commit/3e76c935c2bede285fa8149ac335bf4ae2f01a42
